# Generated by Selenium IDE
from models.group import Group


def test_add_group(app):
    app.group.create(Group(name="test", header="1234", footer="werw"))


def test_add_empty_group(app):
    app.group.create(Group(name="", header="", footer=""))
